export const INITIAL_PLAYERS = [
  // Quarterbacks (QB)
  {
    id: 'p1',
    name: 'Patrick Mahomes',
    position: 'QB',
    team: 'KC',
    injuryStatus: 'Healthy',
    projectedPoints: 21.5,
    weeklyPoints: [22.4, 18.2, 24.1, 19.8, 23.0],
    stats: { passingYds: 310, passingTds: 2, interceptions: 1, rushingYds: 25 },
    rank: 1,
  },
  {
    id: 'p2',
    name: 'Josh Allen',
    position: 'QB',
    team: 'BUF',
    injuryStatus: 'Healthy',
    projectedPoints: 22.8,
    weeklyPoints: [25.1, 21.0, 26.4, 20.2, 24.1],
    stats: { passingYds: 280, passingTds: 2, interceptions: 1, rushingYds: 45, rushingTds: 1 },
    rank: 2,
  },
  {
    id: 'p3',
    name: 'Lamar Jackson',
    position: 'QB',
    team: 'BAL',
    injuryStatus: 'Healthy',
    projectedPoints: 23.2,
    weeklyPoints: [28.4, 19.1, 24.8, 27.5, 22.1],
    stats: { passingYds: 210, passingTds: 1, interceptions: 0, rushingYds: 78, rushingTds: 1 },
    rank: 3,
  },
  {
    id: 'p4',
    name: 'Jalen Hurts',
    position: 'QB',
    team: 'PHI',
    injuryStatus: 'Questionable',
    projectedPoints: 20.8,
    weeklyPoints: [23.5, 24.8, 17.5, 21.0, 19.5],
    stats: { passingYds: 230, passingTds: 1, interceptions: 1, rushingYds: 52, rushingTds: 2 },
    rank: 4,
  },
  {
    id: 'p5',
    name: 'Joe Burrow',
    position: 'QB',
    team: 'CIN',
    injuryStatus: 'Healthy',
    projectedPoints: 19.4,
    weeklyPoints: [18.5, 22.1, 15.6, 23.4, 20.2],
    stats: { passingYds: 305, passingTds: 3, interceptions: 1 },
    rank: 8,
  },
  {
    id: 'p6',
    name: 'C.J. Stroud',
    position: 'QB',
    team: 'HOU',
    injuryStatus: 'Healthy',
    projectedPoints: 18.9,
    weeklyPoints: [20.4, 17.8, 21.1, 19.4, 22.0],
    stats: { passingYds: 290, passingTds: 2, interceptions: 0 },
    rank: 12,
  },

  // Running Backs (RB)
  {
    id: 'p11',
    name: 'Christian McCaffrey',
    position: 'RB',
    team: 'SF',
    injuryStatus: 'Healthy',
    projectedPoints: 22.1,
    weeklyPoints: [24.5, 21.8, 25.1, 20.4, 26.2],
    stats: { rushingYds: 105, rushingTds: 1, receptions: 6, receivingYds: 45 },
    rank: 5,
  },
  {
    id: 'p12',
    name: 'Breece Hall',
    position: 'RB',
    team: 'NYJ',
    injuryStatus: 'Healthy',
    projectedPoints: 19.1,
    weeklyPoints: [16.4, 22.8, 18.2, 19.5, 21.1],
    stats: { rushingYds: 85, rushingTds: 1, receptions: 5, receivingYds: 38 },
    rank: 6,
  },
  {
    id: 'p13',
    name: 'Bijan Robinson',
    position: 'RB',
    team: 'ATL',
    injuryStatus: 'Healthy',
    projectedPoints: 18.5,
    weeklyPoints: [17.1, 19.5, 21.0, 16.8, 20.4],
    stats: { rushingYds: 92, rushingTds: 1, receptions: 4, receivingYds: 28 },
    rank: 7,
  },
  {
    id: 'p14',
    name: 'Saquon Barkley',
    position: 'RB',
    team: 'PHI',
    injuryStatus: 'Healthy',
    projectedPoints: 17.6,
    weeklyPoints: [21.0, 15.2, 18.4, 22.1, 16.8],
    stats: { rushingYds: 112, rushingTds: 1, receptions: 3, receivingYds: 15 },
    rank: 9,
  },
  {
    id: 'p15',
    name: 'Jonathan Taylor',
    position: 'RB',
    team: 'IND',
    injuryStatus: 'Questionable',
    projectedPoints: 16.2,
    weeklyPoints: [14.5, 18.2, 15.1, 19.0, 12.5],
    stats: { rushingYds: 88, rushingTds: 1, receptions: 2, receivingYds: 12 },
    rank: 14,
  },
  {
    id: 'p16',
    name: 'Kyren Williams',
    position: 'RB',
    team: 'LAR',
    injuryStatus: 'Healthy',
    projectedPoints: 16.9,
    weeklyPoints: [19.2, 17.4, 22.5, 15.1, 18.0],
    stats: { rushingYds: 94, rushingTds: 2, receptions: 2, receivingYds: 10 },
    rank: 15,
  },
  {
    id: 'p17',
    name: 'Jahmyr Gibbs',
    position: 'RB',
    team: 'DET',
    injuryStatus: 'Healthy',
    projectedPoints: 15.8,
    weeklyPoints: [14.1, 16.8, 19.5, 13.2, 18.4],
    stats: { rushingYds: 72, rushingTds: 1, receptions: 4, receivingYds: 31 },
    rank: 18,
  },
  {
    id: 'p18',
    name: 'Derrick Henry',
    position: 'RB',
    team: 'BAL',
    injuryStatus: 'Healthy',
    projectedPoints: 15.2,
    weeklyPoints: [18.0, 14.5, 21.2, 16.1, 13.0],
    stats: { rushingYds: 115, rushingTds: 2 },
    rank: 20,
  },

  // Wide Receivers (WR)
  {
    id: 'p21',
    name: 'Justin Jefferson',
    position: 'WR',
    team: 'MIN',
    injuryStatus: 'Healthy',
    projectedPoints: 21.2,
    weeklyPoints: [23.1, 19.5, 24.8, 22.0, 20.5],
    stats: { receptions: 8, receivingYds: 132, receivingTds: 1 },
    rank: 3,
  },
  {
    id: 'p22',
    name: 'CeeDee Lamb',
    position: 'WR',
    team: 'DAL',
    injuryStatus: 'Healthy',
    projectedPoints: 20.8,
    weeklyPoints: [21.4, 24.2, 18.5, 23.1, 19.8],
    stats: { receptions: 9, receivingYds: 118, receivingTds: 1 },
    rank: 4,
  },
  {
    id: 'p23',
    name: 'Tyreek Hill',
    position: 'WR',
    team: 'MIA',
    injuryStatus: 'Healthy',
    projectedPoints: 21.0,
    weeklyPoints: [28.2, 17.5, 25.4, 18.9, 22.1],
    stats: { receptions: 7, receivingYds: 145, receivingTds: 1 },
    rank: 5,
  },
  {
    id: 'p24',
    name: 'Amon-Ra St. Brown',
    position: 'WR',
    team: 'DET',
    injuryStatus: 'Healthy',
    projectedPoints: 18.4,
    weeklyPoints: [17.5, 19.8, 18.1, 21.4, 19.0],
    stats: { receptions: 10, receivingYds: 102, receivingTds: 1 },
    rank: 10,
  },
  {
    id: 'p25',
    name: "Ja'Marr Chase",
    position: 'WR',
    team: 'CIN',
    injuryStatus: 'Healthy',
    projectedPoints: 18.9,
    weeklyPoints: [15.2, 26.5, 14.8, 22.1, 21.0],
    stats: { receptions: 8, receivingYds: 124, receivingTds: 2 },
    rank: 11,
  },
  {
    id: 'p26',
    name: 'A.J. Brown',
    position: 'WR',
    team: 'PHI',
    injuryStatus: 'Healthy',
    projectedPoints: 17.2,
    weeklyPoints: [16.8, 19.1, 15.4, 21.2, 17.0],
    stats: { receptions: 6, receivingYds: 98, receivingTds: 1 },
    rank: 13,
  },
  {
    id: 'p27',
    name: 'Puka Nacua',
    position: 'WR',
    team: 'LAR',
    injuryStatus: 'Out',
    projectedPoints: 16.5,
    weeklyPoints: [18.2, 19.5, 11.2, 0.0, 0.0],
    stats: { receptions: 0, receivingYds: 0 },
    rank: 16,
  },
  {
    id: 'p28',
    name: 'Garrett Wilson',
    position: 'WR',
    team: 'NYJ',
    injuryStatus: 'Healthy',
    projectedPoints: 15.9,
    weeklyPoints: [13.4, 16.5, 15.2, 18.1, 17.5],
    stats: { receptions: 7, receivingYds: 86, receivingTds: 1 },
    rank: 19,
  },
  {
    id: 'p29',
    name: 'Davante Adams',
    position: 'WR',
    team: 'LV',
    injuryStatus: 'Doubtful',
    projectedPoints: 14.8,
    weeklyPoints: [15.2, 18.1, 12.0, 5.2, 0.0],
    stats: { receptions: 3, receivingYds: 42 },
    rank: 22,
  },

  // Tight Ends (TE)
  {
    id: 'p31',
    name: 'Travis Kelce',
    position: 'TE',
    team: 'KC',
    injuryStatus: 'Healthy',
    projectedPoints: 14.2,
    weeklyPoints: [15.1, 13.4, 16.2, 12.8, 15.0],
    stats: { receptions: 6, receivingYds: 68, receivingTds: 1 },
    rank: 17,
  },
  {
    id: 'p32',
    name: 'Sam LaPorta',
    position: 'TE',
    team: 'DET',
    injuryStatus: 'Healthy',
    projectedPoints: 13.1,
    weeklyPoints: [11.2, 14.5, 15.8, 12.1, 13.4],
    stats: { receptions: 5, receivingYds: 58, receivingTds: 1 },
    rank: 24,
  },
  {
    id: 'p33',
    name: 'Mark Andrews',
    position: 'TE',
    team: 'BAL',
    injuryStatus: 'Healthy',
    projectedPoints: 12.0,
    weeklyPoints: [9.5, 13.1, 11.8, 10.5, 14.2],
    stats: { receptions: 4, receivingYds: 52, receivingTds: 1 },
    rank: 30,
  },
  {
    id: 'p34',
    name: 'Trey McBride',
    position: 'TE',
    team: 'ARI',
    injuryStatus: 'Healthy',
    projectedPoints: 11.5,
    weeklyPoints: [10.2, 12.4, 9.8, 14.1, 11.0],
    stats: { receptions: 6, receivingYds: 61 },
    rank: 35,
  },

  // Kickers (K)
  {
    id: 'p41',
    name: 'Harrison Butker',
    position: 'K',
    team: 'KC',
    injuryStatus: 'Healthy',
    projectedPoints: 8.5,
    weeklyPoints: [9.0, 8.0, 11.0, 7.0, 9.0],
    stats: { fieldGoals: 2, extraPoints: 3 },
    rank: 50,
  },
  {
    id: 'p42',
    name: 'Justin Tucker',
    position: 'K',
    team: 'BAL',
    injuryStatus: 'Healthy',
    projectedPoints: 8.2,
    weeklyPoints: [7.0, 10.0, 8.0, 9.0, 6.0],
    stats: { fieldGoals: 1, extraPoints: 3 },
    rank: 55,
  },
  {
    id: 'p43',
    name: 'Brandon Aubrey',
    position: 'K',
    team: 'DAL',
    injuryStatus: 'Healthy',
    projectedPoints: 9.2,
    weeklyPoints: [12.0, 11.0, 9.0, 13.0, 8.0],
    stats: { fieldGoals: 3, extraPoints: 2 },
    rank: 48,
  },

  // Defense / Special Teams (D/ST)
  {
    id: 'p51',
    name: 'San Francisco 49ers',
    position: 'D/ST',
    team: 'SF',
    injuryStatus: 'Healthy',
    projectedPoints: 8.0,
    weeklyPoints: [7.0, 12.0, 8.0, 6.0, 10.0],
    stats: { sacks: 3, defInt: 1, fumblesRec: 1, pointsAllowed: 17 },
    rank: 45,
  },
  {
    id: 'p52',
    name: 'Baltimore Ravens',
    position: 'D/ST',
    team: 'BAL',
    injuryStatus: 'Healthy',
    projectedPoints: 8.5,
    weeklyPoints: [11.0, 9.0, 7.0, 12.0, 8.0],
    stats: { sacks: 4, defInt: 2, fumblesRec: 0, pointsAllowed: 13 },
    rank: 42,
  },
  {
    id: 'p53',
    name: 'New York Jets',
    position: 'D/ST',
    team: 'NYJ',
    injuryStatus: 'Healthy',
    projectedPoints: 7.8,
    weeklyPoints: [6.0, 13.0, 8.0, 9.0, 5.0],
    stats: { sacks: 3, defInt: 1, fumblesRec: 2, pointsAllowed: 16 },
    rank: 48,
  },
  {
    id: 'p54',
    name: 'Dallas Cowboys',
    position: 'D/ST',
    team: 'DAL',
    injuryStatus: 'Healthy',
    projectedPoints: 7.5,
    weeklyPoints: [8.0, 5.0, 14.0, 7.0, 9.0],
    stats: { sacks: 2, defInt: 1, fumblesRec: 1, pointsAllowed: 21 },
    rank: 52,
  }
];

export const INITIAL_SOCCER_PLAYERS = [
  // Goalkeepers (GK)
  {
    id: 's1',
    name: 'Emiliano Martínez',
    position: 'GK',
    team: 'ARG',
    injuryStatus: 'Healthy',
    projectedPoints: 9.8,
    weeklyPoints: [8.5, 12.0, 10.1, 7.5, 11.0],
    stats: { saves: 5, cleanSheet: true },
    rank: 18,
  },
  {
    id: 's2',
    name: 'Alisson Becker',
    position: 'GK',
    team: 'BRA',
    injuryStatus: 'Healthy',
    projectedPoints: 8.5,
    weeklyPoints: [9.0, 7.5, 11.2, 8.0, 6.8],
    stats: { saves: 4, cleanSheet: true },
    rank: 24,
  },
  {
    id: 's3',
    name: 'Thibaut Courtois',
    position: 'GK',
    team: 'BEL',
    injuryStatus: 'Healthy',
    projectedPoints: 8.0,
    weeklyPoints: [6.5, 10.0, 8.5, 9.2, 5.8],
    stats: { saves: 3, cleanSheet: true },
    rank: 30,
  },
  {
    id: 's4',
    name: 'Jordan Pickford',
    position: 'GK',
    team: 'ENG',
    injuryStatus: 'Healthy',
    projectedPoints: 8.2,
    weeklyPoints: [7.8, 9.1, 6.2, 11.0, 7.0],
    stats: { saves: 4, cleanSheet: false },
    rank: 32,
  },

  // Defenders (DF)
  {
    id: 's11',
    name: 'Virgil van Dijk',
    position: 'DF',
    team: 'NED',
    injuryStatus: 'Healthy',
    projectedPoints: 9.5,
    weeklyPoints: [11.0, 8.2, 10.5, 9.0, 8.8],
    stats: { cleanSheet: true, goals: 0 },
    rank: 14,
  },
  {
    id: 's12',
    name: 'William Saliba',
    position: 'DF',
    team: 'FRA',
    injuryStatus: 'Healthy',
    projectedPoints: 8.8,
    weeklyPoints: [9.2, 11.1, 7.5, 8.4, 9.0],
    stats: { cleanSheet: true },
    rank: 15,
  },
  {
    id: 's13',
    name: 'Achraf Hakimi',
    position: 'DF',
    team: 'MAR',
    injuryStatus: 'Healthy',
    projectedPoints: 10.2,
    weeklyPoints: [12.4, 8.5, 11.0, 9.8, 10.5],
    stats: { assists: 1, shotsOnTarget: 1, cleanSheet: false },
    rank: 11,
  },
  {
    id: 's14',
    name: 'Alphonso Davies',
    position: 'DF',
    team: 'CAN',
    injuryStatus: 'Healthy',
    projectedPoints: 9.2,
    weeklyPoints: [8.5, 11.2, 9.0, 7.8, 10.5],
    stats: { shotsOnTarget: 1, cleanSheet: false },
    rank: 22,
  },
  {
    id: 's15',
    name: 'Marquinhos',
    position: 'DF',
    team: 'BRA',
    injuryStatus: 'Healthy',
    projectedPoints: 8.5,
    weeklyPoints: [6.8, 9.5, 8.2, 10.1, 7.9],
    stats: { cleanSheet: true },
    rank: 25,
  },
  {
    id: 's16',
    name: 'Ronald Araújo',
    position: 'DF',
    team: 'URU',
    injuryStatus: 'Questionable',
    projectedPoints: 7.9,
    weeklyPoints: [8.0, 4.5, 9.2, 7.1, 10.8],
    stats: { cleanSheet: true },
    rank: 35,
  },

  // Midfielders (MF)
  {
    id: 's21',
    name: 'Jude Bellingham',
    position: 'MF',
    team: 'ENG',
    injuryStatus: 'Healthy',
    projectedPoints: 16.4,
    weeklyPoints: [18.2, 14.5, 19.1, 15.0, 15.5],
    stats: { goals: 1, assists: 1, shotsOnTarget: 2 },
    rank: 4,
  },
  {
    id: 's22',
    name: 'Kevin De Bruyne',
    position: 'MF',
    team: 'BEL',
    injuryStatus: 'Healthy',
    projectedPoints: 17.1,
    weeklyPoints: [21.4, 15.8, 18.5, 19.8, 11.0],
    stats: { assists: 2, shotsOnTarget: 2 },
    rank: 5,
  },
  {
    id: 's23',
    name: 'Bruno Fernandes',
    position: 'MF',
    team: 'POR',
    injuryStatus: 'Healthy',
    projectedPoints: 15.8,
    weeklyPoints: [14.0, 18.2, 12.8, 20.4, 14.1],
    stats: { goals: 1, assists: 1 },
    rank: 10,
  },
  {
    id: 's24',
    name: 'Jamal Musiala',
    position: 'MF',
    team: 'GER',
    injuryStatus: 'Healthy',
    projectedPoints: 14.8,
    weeklyPoints: [13.5, 16.2, 15.8, 12.2, 16.5],
    stats: { assists: 1, shotsOnTarget: 2 },
    rank: 12,
  },
  {
    id: 's25',
    name: 'Bukayo Saka',
    position: 'MF',
    team: 'ENG',
    injuryStatus: 'Healthy',
    projectedPoints: 15.2,
    weeklyPoints: [17.5, 13.1, 16.0, 18.2, 11.5],
    stats: { goals: 1, shotsOnTarget: 2 },
    rank: 13,
  },
  {
    id: 's26',
    name: 'Rodri',
    position: 'MF',
    team: 'ESP',
    injuryStatus: 'Healthy',
    projectedPoints: 12.8,
    weeklyPoints: [11.5, 14.0, 12.0, 13.5, 13.0],
    stats: { assists: 1 },
    rank: 15,
  },
  {
    id: 's27',
    name: 'Luka Modrić',
    position: 'MF',
    team: 'CRO',
    injuryStatus: 'Healthy',
    projectedPoints: 11.2,
    weeklyPoints: [10.2, 12.0, 9.8, 11.5, 12.5],
    stats: { assists: 1 },
    rank: 28,
  },

  // Forwards (FW)
  {
    id: 's31',
    name: 'Kylian Mbappé',
    position: 'FW',
    team: 'FRA',
    injuryStatus: 'Healthy',
    projectedPoints: 21.5,
    weeklyPoints: [24.1, 18.5, 23.0, 20.2, 22.4],
    stats: { goals: 2, shotsOnTarget: 5 },
    rank: 1,
  },
  {
    id: 's32',
    name: 'Lionel Messi',
    position: 'FW',
    team: 'ARG',
    injuryStatus: 'Healthy',
    projectedPoints: 20.8,
    weeklyPoints: [22.4, 25.1, 17.5, 19.8, 19.5],
    stats: { goals: 1, assists: 1, shotsOnTarget: 3 },
    rank: 2,
  },
  {
    id: 's33',
    name: 'Erling Haaland',
    position: 'FW',
    team: 'NOR',
    injuryStatus: 'Healthy',
    projectedPoints: 19.8,
    weeklyPoints: [28.4, 19.1, 24.8, 20.2, 17.0],
    stats: { goals: 2, shotsOnTarget: 4 },
    rank: 3,
  },
  {
    id: 's34',
    name: 'Harry Kane',
    position: 'FW',
    team: 'ENG',
    injuryStatus: 'Healthy',
    projectedPoints: 18.5,
    weeklyPoints: [16.4, 21.0, 17.5, 18.9, 19.1],
    stats: { goals: 1, assists: 1, shotsOnTarget: 2 },
    rank: 6,
  },
  {
    id: 's35',
    name: 'Mohamed Salah',
    position: 'FW',
    team: 'EGY',
    injuryStatus: 'Healthy',
    projectedPoints: 18.0,
    weeklyPoints: [19.2, 15.4, 21.2, 17.8, 16.5],
    stats: { goals: 1, assists: 1, shotsOnTarget: 3 },
    rank: 7,
  },
  {
    id: 's36',
    name: 'Cristiano Ronaldo',
    position: 'FW',
    team: 'POR',
    injuryStatus: 'Questionable',
    projectedPoints: 15.0,
    weeklyPoints: [12.0, 16.5, 14.8, 18.1, 13.5],
    stats: { goals: 1, shotsOnTarget: 3 },
    rank: 21,
  },
  {
    id: 's37',
    name: 'Antoine Griezmann',
    position: 'FW',
    team: 'FRA',
    injuryStatus: 'Healthy',
    projectedPoints: 14.5,
    weeklyPoints: [15.2, 13.1, 16.0, 12.8, 15.5],
    stats: { assists: 2, shotsOnTarget: 1 },
    rank: 23,
  }
];

export const SOCCER_TEAMS = [
  { code: 'ARG', name: 'Argentina', primary: '#75AADB' },
  { code: 'FRA', name: 'France', primary: '#213065' },
  { code: 'BRA', name: 'Brazil', primary: '#FFDF00' },
  { code: 'ENG', name: 'England', primary: '#CF081F' },
  { code: 'GER', name: 'Germany', primary: '#000000' },
  { code: 'ESP', name: 'Spain', primary: '#C60B1E' },
  { code: 'POR', name: 'Portugal', primary: '#046A38' },
  { code: 'BEL', name: 'Belgium', primary: '#E30613' },
  { code: 'NED', name: 'Netherlands', primary: '#FF4F00' },
  { code: 'CRO', name: 'Croatia', primary: '#FF0000' },
  { code: 'MAR', name: 'Morocco', primary: '#117A65' },
  { code: 'CAN', name: 'Canada', primary: '#FF0000' },
  { code: 'URU', name: 'Uruguay', primary: '#0081C6' },
  { code: 'NOR', name: 'Norway', primary: '#EF2B2D' },
  { code: 'EGY', name: 'Egypt', primary: '#C09300' }
];

export const MOCK_OPPONENT_OWNERS = [
  { name: 'David G.', avatar: 'D' },
  { name: 'Sarah L.', avatar: 'S' },
  { name: 'Michael C.', avatar: 'M' },
  { name: 'Emma T.', avatar: 'E' },
  { name: 'Rohan P.', avatar: 'R' },
  { name: 'Jessica V.', avatar: 'J' },
  { name: 'Marcus K.', avatar: 'M' },
  { name: 'Olivia H.', avatar: 'O' },
  { name: 'Liam N.', avatar: 'L' }
];

export const FOOTBALL_TEAMS = [
  { code: 'ARI', name: 'Arizona Cardinals', primary: '#A71930' },
  { code: 'ATL', name: 'Atlanta Falcons', primary: '#A71930' },
  { code: 'BAL', name: 'Baltimore Ravens', primary: '#241773' },
  { code: 'BUF', name: 'Buffalo Bills', primary: '#00338D' },
  { code: 'CAR', name: 'Carolina Panthers', primary: '#0085CA' },
  { code: 'CHI', name: 'Chicago Bears', primary: '#0B2265' },
  { code: 'CIN', name: 'Cincinnati Bengals', primary: '#FB4F14' },
  { code: 'CLE', name: 'Cleveland Browns', primary: '#311D00' },
  { code: 'DAL', name: 'Dallas Cowboys', primary: '#003594' },
  { code: 'DEN', name: 'Denver Broncos', primary: '#FB4F14' },
  { code: 'DET', name: 'Detroit Lions', primary: '#0076B6' },
  { code: 'GB', name: 'Green Bay Packers', primary: '#203731' },
  { code: 'HOU', name: 'Houston Texans', primary: '#03202F' },
  { code: 'IND', name: 'Indianapolis Colts', primary: '#002C5F' },
  { code: 'JAX', name: 'Jacksonville Jaguars', primary: '#006778' },
  { code: 'KC', name: 'Kansas City Chiefs', primary: '#E31837' },
  { code: 'LV', name: 'Las Vegas Raiders', primary: '#000000' },
  { code: 'LAC', name: 'Los Angeles Chargers', primary: '#0080C6' },
  { code: 'LAR', name: 'Los Angeles Rams', primary: '#003594' },
  { code: 'MIA', name: 'Miami Dolphins', primary: '#008E97' },
  { code: 'MIN', name: 'Minnesota Vikings', primary: '#4F2683' },
  { code: 'NE', name: 'New England Patriots', primary: '#002244' },
  { code: 'NO', name: 'New Orleans Saints', primary: '#D3BC8D' },
  { code: 'NYG', name: 'New York Giants', primary: '#0B2265' },
  { code: 'NYJ', name: 'New York Jets', primary: '#125740' },
  { code: 'PHI', name: 'Philadelphia Eagles', primary: '#004C54' },
  { code: 'PIT', name: 'Pittsburgh Steelers', primary: '#FFB612' },
  { code: 'SF', name: 'San Francisco 49ers', primary: '#AA0000' },
  { code: 'SEA', name: 'Seattle Seahawks', primary: '#002244' },
  { code: 'TB', name: 'Tampa Bay Buccaneers', primary: '#D50A0A' },
  { code: 'TEN', name: 'Tennessee Titans', primary: '#4B92DB' },
  { code: 'WAS', name: 'Washington Commanders', primary: '#5A1414' }
];
